## schema design for epostal
## for mySQL
## use source to load it into mysql say source EPOSTAL_table.sql from the mysql shell
USE sample_Epostal ;

DROP TABLE IF EXISTS b2b;

CREATE TABLE `b2b`(
  `Sequence` bigint(20) NOT NULL,
  `Company_ID` bigint(20) NOT NULL,
  `company` varchar(150) NOT NULL,
  `prefix` varchar(15) NOT NULL,
  `Full_Name` varchar(110) NOT NULL,
  `first_name` varchar(40) NOT NULL,
  `middle_name` varchar(25) NOT NULL,
  `last_name` varchar(40) NOT NULL,
  `title` varchar(150) NOT NULL,
  `address_1` varchar(40) NOT NULL,
  `address_2` varchar(40) NOT NULL,
  `city` varchar(30) NOT NULL,
  `state` char(2) NOT NULL,
  `zip_code` int(10) NOT NULL,
  `zip4` int(10) NOT NULL,
  `phone` varchar(30) NOT NULL,
  `fax` varchar(30) NOT NULL,
  `sic6` varchar(10) NOT NULL,
  `sic4` varchar(10) NOT NULL,
  `sic2` int(10) NOT NULL,
  `naics` varchar(10) NOT NULL,
  `gender` varchar(1) NOT NULL,
  `web_address` varchar(150) NOT NULL,
  `industry` varchar(150) NOT NULL,
  `email` varchar(75) NOT NULL,
  `email2` varchar(75) NOT NULL,
  `sales_code` varchar(1) NOT NULL,
  `employees_code` varchar(1) NOT NULL,
  `County` varchar(25) NOT NULL,
  `Rank` varchar(2) NOT NULL,
  `Function` varchar(1) NOT NULL,
  `Focus` varchar(2) NOT NULL,
  `TitleRank` varchar(5) NOT NULL,
  `TitleCommon` varchar(32) NOT NULL,
  `Company2` varchar(30) NOT NULL,
  `Company_phone` varchar(10) NOT NULL,
  `Subsidiary_flag` varchar(1) NOT NULL,
  `Manufacturing_flag` varchar(1) NOT NULL,
  `sic8` varchar(8) NOT NULL,
  `Location_type` varchar(1) NOT NULL,
  `carrier_route` varchar(4) NOT NULL,
  `delivery_point` varchar(3) NOT NULL,
  `CMRA` varchar(1) NOT NULL,
  `congressional_district` varchar(2) NOT NULL,
  `county_code` varchar(5) NOT NULL,
  `time_zone_code` varchar(5) NOT NULL,
  `cbsa_code` varchar(5) NOT NULL,
  `cbsa_division_code` varchar(5) NOT NULL,
  `cbsa_division_level` varchar(150) NOT NULL,
  `census_tract` varchar(4) NOT NULL,
  `tract_suffix` varchar(2) NOT NULL,
  `rb_ind` varchar(4) NOT NULL,
  `Facebook_URL` varchar(160) NOT NULL,
  `Flickr_URL` varchar(160) NOT NULL,
  `FourSquare_URL` varchar(160) NOT NULL,
  `GooglePlus_URL` varchar(160) NOT NULL,
  `Gravatar_URL` varchar(160) NOT NULL,
  `LinkedIn_URL` varchar(160) NOT NULL,
  `MySpace_URL` varchar(160) NOT NULL,
  `Picasa_URL` varchar(160) NOT NULL,
  `Pinterest_URL` varchar(160) NOT NULL,
  `Twitter_URL` varchar(160) NOT NULL,
  `Vimeo_URL` varchar(160) NOT NULL,
  `YouTube_URL` varchar(160) NOT NULL,
  `Franchise_Flag` varchar(1) NOT NULL,
  `Corporate_Employee_Code` varchar(50) NOT NULL,
  `Year_Established` varchar(4) NOT NULL,
  `Female_Owned` varchar(1) NOT NULL,
  `Home_Based_Indicator` varchar(1) NOT NULL,
  `Small_Business_Indicator` varchar(1) NOT NULL,
  `Non_Profit_Org` varchar(1) NOT NULL,
  PRIMARY KEY (`Sequence`),
  KEY `id_index` (`Company_ID`) USING BTREE,
  KEY `idx_auto_make_model` (`phone`) USING BTREE
);

LOAD DATA LOCAL  INFILE '/home/ubuntu/V12_B2B_datasample_05232017.csv'  INTO TABLE b2b FIELDS TERMINATED BY ','  ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;
SELECT count(*) from b2b;
#show warnings;

