## schema design for epostal
## for mySQL
## use source to load it into mysql say source EPOSTAL_table.sql from the mysql shell
use sample_postal;
DROP TABLE IF EXISTS cpg;
CREATE TABLE `cpg` (
  `sequence` bigint(20) NOT NULL,
  `CPG_CONFIDENCE` varchar(5) NOT NULL,
  `air_deo_fresh` varchar(5) NOT NULL,
  `other_condiments` varchar(5) NOT NULL,
  `food_storage_bags` varchar(5) NOT NULL,
  `allergy_sinus` varchar(5) NOT NULL,
  `otc_pain_relievers` varchar(5) NOT NULL,
  `antipersp_deoderants` varchar(5) NOT NULL,
  `side_dishes` varchar(5) NOT NULL,
  `baby_feeding_acc` varchar(5) NOT NULL,
  `baby_food_beverage` varchar(5) NOT NULL,
  `baby_formula` varchar(5) NOT NULL,
  `sweet_baked_goods` varchar(5) NOT NULL,
  `baking_prod` varchar(5) NOT NULL,
  `bath_soap` varchar(5) NOT NULL,
  `beers_ales` varchar(5) NOT NULL,
  `bread_buns_rolls` varchar(5) NOT NULL,
  `cakes_pies` varchar(5) NOT NULL,
  `carbonated_beverages` varchar(5) NOT NULL,
  `cat_food_treats` varchar(5) NOT NULL,
  `cereal_energy_bars` varchar(5) NOT NULL,
  `cheese` varchar(5) NOT NULL,
  `chocolate` varchar(5) NOT NULL,
  `hh_cleaning_tools` varchar(5) NOT NULL,
  `coffee` varchar(5) NOT NULL,
  `cookies` varchar(5) NOT NULL,
  `cosmetics` varchar(5) NOT NULL,
  `cough_cold` varchar(5) NOT NULL,
  `crackers` varchar(5) NOT NULL,
  `diapers` varchar(5) NOT NULL,
  `dog_food_treats` varchar(5) NOT NULL,
  `eggs_egg_subst` varchar(5) NOT NULL,
  `first_aid_emerg_sups` varchar(5) NOT NULL,
  `foils_wraps` varchar(5) NOT NULL,
  `fruit` varchar(5) NOT NULL,
  `general_pet` varchar(5) NOT NULL,
  `hair_care` varchar(5) NOT NULL,
  `mexican_dinners_sauces` varchar(5) NOT NULL,
  `hot_cereal` varchar(5) NOT NULL,
  `hh_cleaners` varchar(5) NOT NULL,
  `ice_cream_novelties_sherbert` varchar(5) NOT NULL,
  `jams_jellies` varchar(5) NOT NULL,
  `juices_noncarbonated_bevs` varchar(5) NOT NULL,
  `ketchup` varchar(5) NOT NULL,
  `laundry_detergent` varchar(5) NOT NULL,
  `mayonnaise` varchar(5) NOT NULL,
  `meats` varchar(5) NOT NULL,
  `milk_cream_milk_sub` varchar(5) NOT NULL,
  `mustard` varchar(5) NOT NULL,
  `non_chocolate_candy` varchar(5) NOT NULL,
  `peanut_butter` varchar(5) NOT NULL,
  `nutritional_supp_weight_ctrl` varchar(5) NOT NULL,
  `nuts_trail_mixes` varchar(5) NOT NULL,
  `oral_care` varchar(5) NOT NULL,
  `rice` varchar(5) NOT NULL,
  `pasta_sauce` varchar(5) NOT NULL,
  `poultry` varchar(5) NOT NULL,
  `prepared_meals` varchar(5) NOT NULL,
  `snack_foods` varchar(5) NOT NULL,
  `snacks_appetizers` varchar(5) NOT NULL,
  `eat_cereal` varchar(5) NOT NULL,
  `salad_dressing` varchar(5) NOT NULL,
  `salty_snacks` varchar(5) NOT NULL,
  `sauces_gravy` varchar(5) NOT NULL,
  `seafood` varchar(5) NOT NULL,
  `shaving_hair_removal` varchar(5) NOT NULL,
  `skin_care` varchar(5) NOT NULL,
  `liquor` varchar(5) NOT NULL,
  `teas` varchar(5) NOT NULL,
  `toaster_pastries` varchar(5) NOT NULL,
  `vegetables` varchar(5) NOT NULL,
  `water` varchar(5) NOT NULL,
  `whipped_cream_dessert_toppings` varchar(5) NOT NULL,
  `wine` varchar(5) NOT NULL,
  `yogurt` varchar(5) NOT NULL,
  `baby_bathing_grooming_skincare` varchar(5) NOT NULL,
  `baby_feeding` varchar(5) NOT NULL,
  `diapering_acc` varchar(5) NOT NULL,
  `other_spreads_jams_jellies` varchar(5) NOT NULL,
  PRIMARY KEY (`sequence`)
);

LOAD DATA LOCAL  INFILE '/home/ubuntu/Data_Elements_Postal_CPG_Sample.csv'  INTO TABLE cpg FIELDS TERMINATED BY ','  ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

SELECT count(*) from cpg;
#show warnings